/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import kode.Host;

/**
 *
 * @author USER
 */
public class ListHost extends javax.swing.JFrame {

    /**
     * Creates new form ListHost
     */
    private ArrayList<Host> listHost = new ArrayList<>();
    private ListIterator<Host> listIterator;
    private int size;
    private String id_host, namaHst;
    private double harga;
    
    public ListHost() {
        initComponents();
        
        Host hst = new Host();
        hst.ambilData(listHost);
        
        size = listHost.size();
        listIterator = listHost.listIterator();
        hst = listIterator.next();
        id_host = hst.getId_host();
        namaHst = hst.getNama();
        harga = hst.getHarga();
        
        NamaHost.setText(hst.getNama());
        AlamatHost.setText(hst.getAlamat());
        EmailHost.setText(hst.getEmail());
        NoHost.setText(hst.getNo_hp());
        GambarHost.setIcon(new ImageIcon(getClass().getResource("/resource_image/"+hst.getFoto())));
        HargaHost.setText(String.format("%,.2f", hst.getHarga()));
        if (hst.getRating() == 0)
            RatingHost.setText("-");
        else
            RatingHost.setText("" + hst.getRating());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GambarHost = new javax.swing.JLabel();
        NamaHost = new javax.swing.JLabel();
        AlamatHost = new javax.swing.JLabel();
        LabelFrame = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        labelNo = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmailHost = new javax.swing.JLabel();
        NoHost = new javax.swing.JLabel();
        btnReservasi = new javax.swing.JButton();
        labelRating = new javax.swing.JLabel();
        RatingHost = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelRating1 = new javax.swing.JLabel();
        HargaHost = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NamaHost.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NamaHost.setText("Nama Host");

        AlamatHost.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AlamatHost.setText("Alamat");
        AlamatHost.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LabelFrame.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LabelFrame.setText("Host Penyedia Penginapan");

        btnPrev.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPrev.setText("<");
        btnPrev.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNext.setText(">");
        btnNext.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        labelNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNo.setText("Nomor HP");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelEmail.setText("Email");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Alamat");

        EmailHost.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        EmailHost.setText("Email Host");

        NoHost.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NoHost.setText("Nomor Host");

        btnReservasi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnReservasi.setText("Reservasi di sini");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });

        labelRating.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelRating.setText("Rating");

        RatingHost.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        RatingHost.setText("Rating Host");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("/ 5");

        labelRating1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelRating1.setText("Harga");

        HargaHost.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        HargaHost.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("/ malam");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFrame)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GambarHost, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 220, Short.MAX_VALUE)
                                .addComponent(btnReservasi)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AlamatHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(NamaHost, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRating1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NoHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmailHost, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(HargaHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(RatingHost)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(LabelFrame)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(NamaHost)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(EmailHost))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNo)
                            .addComponent(NoHost))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRating)
                            .addComponent(RatingHost)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRating1)
                            .addComponent(HargaHost)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlamatHost, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(GambarHost, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        if(listIterator.hasPrevious()) {
            Host hst;
            hst = listIterator.previous();
            id_host = hst.getId_host();
            namaHst = hst.getNama();
            harga = hst.getHarga();
            
            NamaHost.setText(hst.getNama());
            AlamatHost.setText(hst.getAlamat());
            EmailHost.setText(hst.getEmail());
            NoHost.setText(hst.getNo_hp());
            GambarHost.setIcon(new ImageIcon(getClass().getResource("/resource_image/"+hst.getFoto())));
            HargaHost.setText(String.format("%,.2f", hst.getHarga()));
            if (hst.getRating() == 0)
                RatingHost.setText("-");
            else
                RatingHost.setText("" + hst.getRating());
        } else {
            JOptionPane.showMessageDialog(null, "Kamu sudah sampai di halaman awal...");
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(listIterator.hasNext()) {
            Host hst;
            hst = listIterator.next();
            id_host = hst.getId_host();
            namaHst = hst.getNama();
            harga = hst.getHarga();
            
            NamaHost.setText(hst.getNama());
            AlamatHost.setText(hst.getAlamat());
            EmailHost.setText(hst.getEmail());
            NoHost.setText(hst.getNo_hp());
            GambarHost.setIcon(new ImageIcon(getClass().getResource("/resource_image/"+hst.getFoto())));
            HargaHost.setText(String.format("%,.2f", hst.getHarga()));
            if (hst.getRating() == 0)
                RatingHost.setText("-");
            else
                RatingHost.setText("" + hst.getRating());
        } else {
            JOptionPane.showMessageDialog(null, "Kamu sudah sampai di halaman terakhir...");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        // TODO add your handling code here:
        
        ReservasiPenginapan rp = new ReservasiPenginapan(id_host, namaHst, harga);
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReservasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListHost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatHost;
    private javax.swing.JLabel EmailHost;
    private javax.swing.JLabel GambarHost;
    private javax.swing.JLabel HargaHost;
    private javax.swing.JLabel LabelFrame;
    private javax.swing.JLabel NamaHost;
    private javax.swing.JLabel NoHost;
    private javax.swing.JLabel RatingHost;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNo;
    private javax.swing.JLabel labelRating;
    private javax.swing.JLabel labelRating1;
    // End of variables declaration//GEN-END:variables
}
