/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class RiwayatPesananHost extends javax.swing.JFrame {
    public PreparedStatement pstmt = null;
    public ResultSet rs;
    Connection cn = koneksi.Koneksi.Koneksi();
    
    private String id_host;
    /**
     * Creates new form RiwayatReservasi
     * @param
     */

    /**
     * Creates new form RiwayatPesananHost
     */
    public RiwayatPesananHost(String id_host) {
        initComponents();
         getContentPane().setBackground(new java.awt.Color(187,55,26));
        this.id_host = id_host;
        ShowTable();
        btnUbah.setVisible(false);
        pilUbah.setVisible(false);
    }
    
    public RiwayatPesananHost(){
        initComponents();
        getContentPane().setBackground(new java.awt.Color(187,55,26));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        labelNomor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pilUbah = new javax.swing.JComboBox<>();
        btnUbah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pesanan", "Nama Pemesan", "Nama Hewan", "Jenis", "Umur", "Makanan Favorit", "Catatan", "Voucher", "Layanan", "Check In", "Check Out", "Total", "Total Bayar", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 228, 183));
        jLabel1.setText("Pesanan Nomor: ");

        labelNomor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 228, 183));
        jLabel2.setText("Status Pesanan: ");

        pilUbah.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        pilUbah.setForeground(new java.awt.Color(170, 58, 58));
        pilUbah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum", "Selesai" }));

        btnUbah.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(170, 58, 58));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 228, 183));
        jLabel3.setText("Riwayat Reservasi di Penginapan Kamu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUbah)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(312, 312, 312)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(pilUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if ("Belum".equals(jTable1.getValueAt(jTable1.getSelectedRow(), 13).toString())) {
            btnUbah.setVisible(true);
            pilUbah.setVisible(true);
        } else {
            btnUbah.setVisible(false);
            pilUbah.setVisible(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String id_p = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String stts = (String) pilUbah.getSelectedItem();
        String sql = "UPDATE pesanan SET status='"+stts+"' WHERE id_pesanan='"+id_p+"'";
        
        try {
            Statement st = cn.createStatement();
            st.addBatch(sql);
                    
            st.executeBatch();
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            new RiwayatPesananHost(id_host).setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(RiwayatPesananHost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ShowTable() {
        try{
            String sql = "SELECT p.status, p.id_pesanan, u.nama, p.nama_hewan, p.jenis, p.umur, p.makanan_fav_hewan, p.catatan, p.voucher, p.layanan, p.check_in, p.check_out, p.total, p.total_bayar FROM user u JOIN pesanan p ON p.id_user = u.id WHERE p.id_host = '"+id_host+"'";
            pstmt = cn.prepareStatement(sql);
            rs = pstmt.executeQuery();
            
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
            String[] data = new String[14];
            
            while(rs.next()){
                data[0] = rs.getString("p.id_pesanan");
                data[1] = rs.getString("u.nama");
                data[2] = rs.getString("p.nama_hewan");
                data[3] = rs.getString("p.jenis");
                data[4] = rs.getString("p.umur");
                data[5] = rs.getString("p.makanan_fav_hewan");
                data[6] = rs.getString("p.catatan");
                data[7] = rs.getString("p.voucher");
                data[8] = rs.getString("p.layanan");
                data[9] = rs.getString("p.check_in");
                data[10] = rs.getString("p.check_out");
                data[11] = rs.getString("p.total");
                data[12] = rs.getString("p.total_bayar");
                data[13] = rs.getString("p.status");
                dtm.addRow(data);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatPesananHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatPesananHost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNomor;
    private javax.swing.JComboBox<String> pilUbah;
    // End of variables declaration//GEN-END:variables
}
